<?php

App::uses('AppController', 'Controller');

/**
 * Logs Controller
 * Owner: Abdul Jalil
 * http://www.softwareend.com
 * @property Log $Log
 * @property PaginatorComponent $Paginator
 */
class LogsController extends AppController {

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator');

    /**
     * index method
     * Generated by Abdul Jalil
     * @return void
     */
    public function index() {
        $this->loadModel('User');
        if (isset($this->request->data['btndelete'])) {
            $last = $this->Log->find('first', array('fields' => array('Log.id'), 'order' => array('Log.id' => 'DESC'), 'recursive' => -1));
            $this->Log->query('DELETE FROM logs WHERE id < ' . ($last['Log']['id'] - 1000));
        }
        $users = $this->User->find('list');
        
        $this->set(compact('users'));
        $this->Log->recursive = 0;
        $conditions = array();
        if(($this->request->is('post') || $this->request->is('put')) && isset($this->request->data['Log'])){
            $filter_url['controller'] = $this->request->params['controller'];
            $filter_url['action'] = $this->request->params['action'];
            $filter_url['page'] = 1;
            foreach($this->request->data['Log'] as $name => $value){
                if($value){
                    $filter_url[$name] = trim($value);
                }
            }   
            return $this->redirect($filter_url);
        } else {
            foreach($this->params['named'] as $param_name => $value){

                if($param_name == "frommonth" ){
                    $frommonth=$value;
                }
                if($param_name == "tomonth" ){
                    $tomonth=$value;
                }
                if(!in_array($param_name, array('page','sort','direction','limit'))){
                    if($param_name == "frommonth" || $param_name == "tomonth"){
                        if(!empty($tomonth)){
                            $conditions['OR'] = array(
                               array("DATE_FORMAT(Log.created,'%Y-%m-%d') BETWEEN '" .$frommonth ."' AND '" .$tomonth ."'")
                            );
                        }
                        else{
                            $conditions['OR'] = array(
                                array("DATE_FORMAT(Log.created,'%Y-%m-%d') BETWEEN '" .$frommonth ."' AND '" .$frommonth ."'")
                            );
                        }
                    }elseif($param_name =='status') {
                         $conditions['Log.status'] = $value;
                    }else{
                         $conditions['Log.'.$param_name] = $value;
                    }                   
                    $this->request->data['Log'][$param_name] = $value;
                }
            }
        }
        $this->paginate = array('conditions' => $conditions, 'order' => array('Log.created' => 'DESC'));
        $this->set('logs', $this->paginate());
    }

    /**
     * delete method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function delete($id = null) {
        $this->Log->id = $id;
        if (!$this->Log->exists()) {
            throw new NotFoundException(__('Invalid log'));
        }
        $this->request->allowMethod('post', 'delete');
        if ($this->Log->delete()) {
            $this->Session->setFlash(__('The log has been deleted.'), array('class' => 'alert-success'));
        } else {
            $this->Session->setFlash(__('The log could not be deleted. Please, try again.'), array('class' => 'alert-danger'));
        }
        return $this->redirect(array('action' => 'index'));
    }

    /**
     * delete method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function deleteleft($id = null) {
        $this->Log->id = $id;
        if (!$this->Log->exists()) {
            throw new NotFoundException(__('Invalid log'));
        }
        $this->request->allowMethod('post', 'delete');
        if ($this->Log->delete()) {
            $this->Session->setFlash(__('The log has been deleted.'), array('class' => 'alert-success'));
        } else {
            $this->Session->setFlash(__('The log could not be deleted. Please, try again.'), array('class' => 'alert-danger'));
        }
        return $this->redirect(array('action' => 'index'));
    }

}
