<?php

App::uses('AppController', 'Controller');

/**
 * Roles Controller
 * Owner: Abdul Jalil
 * http://www.softwareend.com
 * @property Role $Role
 * @property PaginatorComponent $Paginator
 */
class RolesController extends AppController {

    /**
     * Components
     *
     * @var array
     */
    public $components = array('Paginator');

    /**
     * index method
     * Generated by Abdul Jalil
     * @return void
     */
    public function index() {
        $this->Role->recursive = 0;
        $this->paginate=['order'=>'Role.serialby ASC'];
        $this->set('role_ids', $this->Paginator->paginate());
    }

    /**
     * view method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function view($id = null) {
        if (!$this->Role->exists($id)) {
            throw new NotFoundException(__('Invalid role_id'));
        }
        $options = array('conditions' => array('Role.' . $this->Role->primaryKey => $id));
        $this->set('role_id', $this->Role->find('first', $options));
    }

    /**
     * add method
     *
     * @return void
     */
    public function add() {
        if ($this->request->is('post')) {
            $this->Role->create();
            $this->request->data['Role']['roles'] = json_encode($this->request->data['Role']['roles']);
            if ($this->Role->save($this->request->data)) {
                $this->Session->setFlash(__('The role_id has been saved.'), array('class' => 'alert-success'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Session->setFlash(__('The role_id could not be saved. Please, try again.'), array('class' => 'alert-danger'));
            }
        }
        
        $this->set('menudata', $this->getmenues());
    }

    /**
     * edit method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function edit($id = null) {
        if (!$this->Role->exists($id)) {
            throw new NotFoundException(__('Invalid role_id'));
        }
        if ($this->request->is(array('post', 'put'))) {
             $this->request->data['Role']['roles'] = json_encode($this->request->data['Role']['roles']);

  
            if ($this->Role->save($this->request->data)) {
                $this->Session->setFlash(__('The role_id has been updated.'), array('class' => 'alert-success'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Session->setFlash(__('The role_id could not be updated. Please, try again.'), array('class' => 'alert-danger'));
            }
        } else {
            $options = array('conditions' => array('Role.' . $this->Role->primaryKey => $id));
            $this->request->data = $this->Role->find('first', $options);
            $this->set('menudata', $this->getmenues());
        }
    }

    /**
     * delete method
     *
     * @throws NotFoundException
     * @param string $id
     * @return void
     */
    public function delete($id = null) {
        $this->Role->id = $id;
        if (!$this->Role->exists()) {
            throw new NotFoundException(__('Invalid role_id'));
        }
        $this->request->allowMethod('post', 'delete');
        if ($this->Role->delete()) {
            $this->Session->setFlash(__('The role_id has been deleted.'), array('class' => 'alert-success'));
        } else {
            $this->Session->setFlash(__('The role_id could not be deleted. Please, try again.'), array('class' => 'alert-danger'));
        }
        return $this->redirect(array('action' => 'index'));
    }

}
